2025-03-22 18:14:49,964 - my_logger - INFO - DevicesApp.py:172 - 截图功能错误list index out of range
2025-03-22 18:14:49,965 - my_logger - INFO - DevicesApp.py:184 - show_screen_pic_error_{e}
2025-03-22 18:16:22,853 - my_logger - INFO - DevicesApp.py:172 - screen_pic_failed_list index out of range
2025-03-22 18:16:22,854 - my_logger - INFO - DevicesApp.py:184 - show_screen_pic_error_'NoneType' object has no attribute 'read'
2025-03-22 19:22:29,761 - my_logger - INFO - DevicesApp.py:174 - screen_pic_failed_list index out of range
2025-03-22 19:22:29,762 - my_logger - INFO - DevicesApp.py:186 - show_screen_pic_error_'NoneType' object has no attribute 'read'
2025-03-22 19:45:31,215 - my_logger - INFO - DevicesApp.py:190 - show_screen_pic_error_'NoneType' object has no attribute 'read'
2025-03-22 19:45:59,750 - my_logger - INFO - DevicesApp.py:190 - show_screen_pic_error_'NoneType' object has no attribute 'read'
2025-03-22 19:47:15,615 - my_logger - INFO - DevicesApp.py:190 - show_screen_pic_error_'NoneType' object has no attribute 'read'
2025-03-22 19:47:50,792 - my_logger - INFO - DevicesApp.py:190 - show_screen_pic_error_'NoneType' object has no attribute 'read'
